export const FALLBACK_TOURS = [
  {
    id: 'sample-1',
    title: 'Autumn in Hunza & Attabad Lake Expedition',
    description: `Experience the breathtaking golden autumn shades of Hunza Valley against snow-crested 7,000m Karakoram giants. 

This curated expedition takes you through the legendary Karakoram Highway, visiting the ancient 900-year-old Altit and Baltit forts, boating across the turquoise waters of Attabad Lake, and gazing upon the dramatic Passu Cones.

Accompanied by veteran mountain guides, travelers enjoy warm Hunzakut hospitality, traditional walnut cakes, stargazing over Rakaposhi viewpoint, and comfortable private transport.`,
    category: 'ADVENTURE',
    price: 68000,
    duration: 6,
    capacity: 15,
    availableSeats: 5,
    bookingsCount: 10,
    startDate: '2026-10-15T00:00:00.000Z',
    endDate: '2026-10-21T00:00:00.000Z',
    departureCity: 'Islamabad',
    destinationCity: 'Hunza Valley',
    location: 'Gilgit-Baltistan, Pakistan',
    meetingPoint: 'I-8 Markaz, Islamabad at 5:30 AM',
    cancellationPolicy: 'Free cancellation up to 7 days before departure. 50% refund within 3 days.',
    includedServices: [
      'Luxury air-conditioned Grand Cabin / Coaster transport',
      '5 Nights hotel accommodations (Double & Triple occupancy)',
      'Daily breakfast and traditional dinner buffet',
      'Attabad Lake boating excursion & life jackets',
      'All toll taxes, bridge passes, and expert tour escort',
    ],
    excludedServices: [
      'Personal luggage porter services & laundry',
      'Lunch and snacks outside specified meals',
      'Fort entrance tickets & personal medical expenses',
    ],
    itinerary: [
      'Day 1: Departure from Islamabad via Hazara Motorway. Stopover at Besham & Chilas. Night stay in Chilas.',
      'Day 2: Scenic drive to Hunza Valley with photo stops at Rakaposhi Viewpoint and 3 Mountain Ranges Junction. Evening stroll in Karimabad.',
      'Day 3: Explore the 900-year-old Altit Fort, Royal Gardens, and Baltit Fort. Sunset photography at Eagle\'s Nest Duikar.',
      'Day 4: Day trip to Attabad Lake, Passu Cones, and Hussaini Suspension Bridge. Boating and local food tasting in Gulmit.',
      'Day 5: Drive to Gilgit, visit historic suspension bridge and local dry fruit market. Overnight stay in Naran / Chilas.',
      'Day 6: Return journey to Islamabad via Babusar Top / Abbottabad. Arrival in capital by evening.',
    ],
    images: [
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=80',
    ],
    faqs: [
      {
        question: 'What kind of clothing should I pack for autumn in Hunza?',
        answer: 'Days are pleasantly sunny (15-20°C) while nights can drop to 3-5°C. Pack warm fleece layers, a windbreaker jacket, comfortable walking shoes, and sunglasses.',
      },
      {
        question: 'Is this tour family-friendly?',
        answer: 'Yes! The transport is comfortable, and all destinations have paved access with easy walking suitable for children and seniors.',
      },
    ],
    status: 'PUBLISHED',
    organizer: {
      id: 'org-1',
      name: 'Karakoram Mountain Guides',
      bio: 'Pioneering high-altitude tours & certified eco-tourism adventures across Gilgit-Baltistan for over 12 years.',
      profilePicture: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    },
  },
  {
    id: 'sample-2',
    title: 'Skardu, Deosai Plains & Shangrila Resort',
    description: `A tranquil 7-day northern odyssey through the land of giants and alpine lakes.

Travel through the scenic Skardu valley, marvel at Upper and Lower Kachura Lakes, explore the mythical cold desert of Sarfaranga, and cross the world's second-highest alpine plateau: Deosai National Park.`,
    category: 'LUXURY',
    price: 85000,
    duration: 7,
    capacity: 12,
    availableSeats: 3,
    bookingsCount: 9,
    startDate: '2026-09-25T00:00:00.000Z',
    endDate: '2026-10-02T00:00:00.000Z',
    departureCity: 'Islamabad',
    destinationCity: 'Skardu',
    location: 'Baltistan, Pakistan',
    meetingPoint: 'Islamabad International Airport / Serena Hotel',
    cancellationPolicy: 'Flexible cancellation up to 5 days before departure.',
    includedServices: [
      '4x4 Prado / Revo transport for Deosai Plains safari',
      '6 Nights in premium 4-star mountain view resorts',
      'Daily breakfast and executive buffet dinners',
      'Cold Desert quad bike experience assistance',
    ],
    excludedServices: [
      'Air tickets (available on request)',
      'Personal tips and beverage charges',
    ],
    itinerary: [
      'Day 1: Scenic flight or drive to Skardu. Check-in at Shangrila Resort.',
      'Day 2: Visit Upper Kachura Lake and trout fish farms.',
      'Day 3: Full-day 4x4 safari across Deosai National Park and Sheosar Lake.',
      'Day 4: Visit Manthal Buddha Rock and historic Kharpocho Fort.',
      'Day 5: Sarfaranga Cold Desert sunset dunes and photography.',
      'Day 6: Shigar Fort and fruit orchard strolls.',
      'Day 7: Farewell breakfast and return journey.',
    ],
    images: [
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1400&q=80',
    ],
    faqs: [
      {
        question: 'How is the mobile network in Skardu and Deosai?',
        answer: 'SCOM and Zong work well in Skardu town and Shangrila. Deosai plateau has limited to zero connectivity, providing a peaceful escape.',
      },
    ],
    status: 'PUBLISHED',
    organizer: {
      id: 'org-2',
      name: 'Baltistan Treks & Safaris',
      bio: 'Luxury hospitality & certified expedition management in Baltistan.',
      profilePicture: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80',
    },
  },
  {
    id: 'sample-3',
    title: 'Fairy Meadows & Nanga Parbat Base Camp Trek',
    description: `The crown jewel of Pakistan trekking. Hike through whispering pine forests to Fairy Meadows, where the north face of Nanga Parbat (8,126m) rises directly before your eyes.`,
    category: 'HIKING',
    price: 52000,
    duration: 5,
    capacity: 18,
    availableSeats: 8,
    bookingsCount: 10,
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2026-10-06T00:00:00.000Z',
    departureCity: 'Rawalpindi',
    destinationCity: 'Fairy Meadows',
    location: 'Diamer District, Gilgit-Baltistan',
    meetingPoint: 'Faizabad Terminal, Rawalpindi at 8:00 PM',
    cancellationPolicy: 'Moderate policy: 75% refund up to 7 days prior.',
    includedServices: [
      'Dedicated mountain 4x4 Jeep transfer from Raikot Bridge to Tattu',
      'Wooden cottage / alpine tent camping at Fairy Meadows',
      'Certified mountain guide and porter support',
      'Bonfire & traditional BBQ night',
    ],
    excludedServices: [
      'Personal riding horses / mules',
      'Sleeping bags (rental available)',
    ],
    itinerary: [
      'Day 1: Night departure from Rawalpindi via Hazara Motorway.',
      'Day 2: Reach Raikot Bridge. Exhilarating 4x4 Jeep ride to Tattu, followed by a 3-hour hike to Fairy Meadows.',
      'Day 3: Day hike to Beyal Camp and Nanga Parbat Base Camp viewpoint.',
      'Day 4: Leisure day at Reflection Lake and pine woods exploration.',
      'Day 5: Hike down to Tattu, Jeep ride back to Raikot, and return drive to Islamabad.',
    ],
    images: [
      'https://images.unsplash.com/photo-1426604966848-d7adac402bff?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=80',
    ],
    faqs: [
      {
        question: 'How difficult is the hike from Tattu to Fairy Meadows?',
        answer: 'It is a moderate 3 to 3.5 hour hike on a wide trail. Horses are also available for hire for anyone preferring to ride.',
      },
    ],
    status: 'PUBLISHED',
    organizer: {
      id: 'org-3',
      name: 'Alpine Club Pakistan',
      bio: 'Certified mountaineering guides and backcountry trekking specialists.',
      profilePicture: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    },
  },
  {
    id: 'sample-4',
    title: 'Swat Valley, Malam Jabba & Kalam River Tour',
    description: `Discover the lush green landscapes of Swat, known as the Switzerland of Pakistan. Visit the Malam Jabba ski resort, scenic Mahodand Lake, and the tranquil roaring Kalam river.`,
    category: 'FAMILY',
    price: 42000,
    duration: 4,
    capacity: 20,
    availableSeats: 12,
    bookingsCount: 8,
    startDate: '2026-10-10T00:00:00.000Z',
    endDate: '2026-10-14T00:00:00.000Z',
    departureCity: 'Peshawar',
    destinationCity: 'Swat Valley',
    location: 'Khyber Pakhtunkhwa, Pakistan',
    meetingPoint: 'Hayatabad Phase 3, Peshawar at 7:00 AM',
    cancellationPolicy: 'Full refund up to 3 days before trip.',
    includedServices: [
      'AC Transport from Peshawar & Islamabad',
      '3-star river-view hotel stays in Kalam',
      '4x4 Jeep excursion to Mahodand Lake',
      'All toll taxes & sightseeing tickets',
    ],
    excludedServices: [
      'Chairlift and zipline tickets at Malam Jabba',
      'Personal shopping and laundry',
    ],
    itinerary: [
      'Day 1: Departure for Swat. Visit White Palace Marghazar. Night stay in Mingora.',
      'Day 2: Visit Malam Jabba ski resort, chairlift ride, and proceed to Kalam valley.',
      'Day 3: Full-day 4x4 Jeep trip to Mahodand Lake, Saifullah Lake, and Ushu Forest.',
      'Day 4: Morning river walk in Kalam, shopping for Swati shawls, and return journey.',
    ],
    images: [
      'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1439853941329-a99ce0457e8a?auto=format&fit=crop&w=1400&q=80',
    ],
    faqs: [
      {
        question: 'Is Swat safe for family travel?',
        answer: 'Extremely safe and hospitable! Tourism is vibrant, and the roads are well-maintained with motorway access almost all the way to Mingora.',
      },
    ],
    status: 'PUBLISHED',
    organizer: {
      id: 'org-4',
      name: 'Swat Heritage Tours',
      bio: 'Local Pashtun hospitality and family guided vacations in northern KP.',
      profilePicture: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    },
  },
];
